#! /bin/sh

SCRIPT=$(readlink -f "$0")
SCRIPT_DIR=$(dirname "$SCRIPT")

# shellcheck source=common
. "${SCRIPT_DIR}/common"

########################################################################

CUR_DIR=$(pwd)

cd "${PARSER_PROJ_DIR}" || exit 1

if [ $# -eq 0 ]; then
  printf "Cleaning generated source\n"
fi

rm -rf src/parser.c
rm -rf src/grammar.json src/node-types.json
rm -rf src/tree_sitter

cd "${CUR_DIR}" || exit 1

if [ $# -eq 0 ]; then
  printf "Done\n"
fi


