#! /bin/sh

SCRIPT=$(readlink -f "$0")
SCRIPT_DIR=$(dirname "$SCRIPT")

# shellcheck source=common
. "${SCRIPT_DIR}/common"

########################################################################

CUR_DIR=$(pwd)

cd "${PARSER_PROJ_DIR}" || exit 1

printf "Cleaning\n"

printf "* Generated source\n"
"${SCRIPT_DIR}"/clean-gen-src 1

printf "* Build directory\n"
"${SCRIPT_DIR}"/clean-build-dir 1

printf "* Wasm file\n"
"${SCRIPT_DIR}"/clean-wasm-file 1

cd "${CUR_DIR}" || exit 1

printf "Done\n"
