#! /bin/sh

SCRIPT=$(readlink -f "$0")
SCRIPT_DIR=$(dirname "$SCRIPT")

# shellcheck source=common
. "${SCRIPT_DIR}/common"

########################################################################

CUR_DIR=$(pwd)

cd "${PARSER_PROJ_DIR}" || exit 1

if [ -f src/parser.c ]; then
  printf "Found src/parser.c, running corpus tests.\n"
else
  printf "Failed to find grammar.js...exiting\n"
  exit 1;
fi

printf "* Invoking tree-sitter test subcommand\n"
${TS_PATH} test

cd "${CUR_DIR}" || exit 1

printf "Done\n"
