#! /bin/sh

#set -o pipefail

SCRIPT=$(readlink -f "$0")
SCRIPT_DIR=$(dirname "$SCRIPT")

# shellcheck source=common
. "${SCRIPT_DIR}/common"

########################################################################

CUR_DIR=$(pwd)

cd "${PARSER_PROJ_DIR}" || exit 1

if [ -f "${SO_INSTALL_DIR}/${SO_NAME}" ]; then
  printf "Found installed shared object, uninstalling.\n"
else
  printf "Failed to find installed shared object...exiting\n"
  exit 1;
fi

printf "* Removing installed shared object\n"

rm -rf "${INSTALLED_SO_PATH}"

cd "${CUR_DIR}" || exit 1

printf "Done\n"
