#! /bin/sh

UNAME_S=$(uname -s)

case ${UNAME_S} in
    Linux)
        SYS_TYPE=Linux
        ;;
    Darwin)
        SYS_TYPE=Darwin
        ;;
    MINGW64*)
        SYS_TYPE=MINGW64
        ;;
    *)
        # XXX: warn?
        SYS_TYPE=UNKNOWN
        ;;
esac

case ${SYS_TYPE} in
    Linux)
        SO_EXT=so
        ;;
    Darwin)
        SO_EXT=dylib
        ;;
    MINGW64)
        SO_EXT=dll
        ;;
    *)
        # XXX: warn?
        SO_EXT=so
        ;;
esac

echo "${SO_EXT}"
